#!/bin/bash
# iOS Image Debugging - Real-time Log Monitor
# Run this while testing on iOS to see exactly what's happening

echo "=================================================="
echo "iOS REFERENCE IMAGE DEBUGGING"
echo "=================================================="
echo ""
echo "This will show you real-time logs as your iOS device"
echo "requests reference images."
echo ""
echo "INSTRUCTIONS:"
echo "1. In another terminal, start tailing these logs:"
echo ""
echo "   Console output:"
echo "   tail -f /tmp/job_service_ios_debug.log"
echo ""
echo "   Structured JSON logs:"
echo "   tail -f /Users/shaydu/dev/mondrian-macos/.cursor/debug.log | grep ios-image-debug"
echo ""
echo "2. In your iOS app:"
echo "   - Run an analysis"
echo "   - Wait for it to complete"
echo "   - Scroll to Reference Images section"
echo ""
echo "3. Look at the logs for:"
echo "   ✓ '[iOS DEBUG] Reference image request' - confirms server received request"
echo "   ✓ '[iOS DEBUG] Found reference image file' - confirms file exists"
echo "   ✓ '[iOS DEBUG] Serving reference image successfully' - image was sent"
echo ""
echo "   ✗ 'Reference image not found' - file doesn't exist"
echo "   ✗ 'Failed to serve reference image' - error reading file"
echo ""
echo "4. Check the display_url in the logs:"
echo "   Should contain: http://192.168.x.x:5005/api/reference-image/..."
echo "   NOT: /api/reference-image/... (relative path won't work on iOS)"
echo ""
echo "5. Share these log outputs to debug:"
echo "   - Screenshots from iOS showing broken images"
echo "   - Output of: grep 'ios-image-debug' /Users/shaydu/dev/mondrian-macos/.cursor/debug.log | tail -20"
echo "   - Output of: tail -30 /tmp/job_service_ios_debug.log"
echo ""
echo "=================================================="
