#!/usr/bin/env python3
"""
Add/update disclaimer text in database config.
This allows the disclaimer to be easily changed across all exports and analysis outputs.

Usage:
    python3 update_disclaimer.py              # Updates with default disclaimer
    python3 update_disclaimer.py --show      # Shows current disclaimer
"""

import sqlite3
import sys
import os
from pathlib import Path

# Get database path
ROOT = Path(__file__).resolve().parent
DB_PATH = str(ROOT / 'mondrian.db')

# Default disclaimer text
DEFAULT_DISCLAIMER = """AI-Generated Analysis: This report is generated by artificial intelligence and represents a simulated perspective of the named advisor. It is not a professional critique from an actual photographer or art expert.

Creative Guidance Only: These recommendations should be used as creative guidance and inspiration, not as definitive professional advice. Individual artistic interpretation and personal vision may vary.

Not Professional Advice: This analysis is not a substitute for professional photography instruction, mentorship, or critique. For professional assessment, consult with qualified photography educators or critics."""

def set_disclaimer(db_path: str, disclaimer_text: str) -> bool:
    """Set the disclaimer text in the config table"""
    try:
        conn = sqlite3.connect(db_path, timeout=5)
        cursor = conn.cursor()
        
        # Check if disclaimer already exists
        cursor.execute("SELECT value FROM config WHERE key = 'disclaimer'")
        result = cursor.fetchone()
        
        if result:
            cursor.execute("UPDATE config SET value = ? WHERE key = 'disclaimer'", (disclaimer_text,))
            print("✓ Updated existing disclaimer")
        else:
            cursor.execute("INSERT INTO config (key, value) VALUES ('disclaimer', ?)", (disclaimer_text,))
            print("✓ Inserted new disclaimer")
        
        conn.commit()
        conn.close()
        return True
    except Exception as e:
        print(f"✗ Error setting disclaimer: {e}")
        return False

def get_disclaimer(db_path: str) -> str:
    """Get the disclaimer text from the config table"""
    try:
        conn = sqlite3.connect(db_path, timeout=5)
        cursor = conn.cursor()
        cursor.execute("SELECT value FROM config WHERE key = 'disclaimer'")
        result = cursor.fetchone()
        conn.close()
        
        if result:
            return result[0]
        return ""
    except Exception as e:
        print(f"✗ Error getting disclaimer: {e}")
        return ""

def main():
    print("=" * 70)
    print("Disclaimer Configuration")
    print("=" * 70)
    
    # Check if database exists
    if not os.path.exists(DB_PATH):
        print(f"✗ Database not found: {DB_PATH}")
        print("Initialize database first: python3 init_database.py")
        return 1
    
    if len(sys.argv) > 1 and sys.argv[1] == '--show':
        # Show current disclaimer
        current = get_disclaimer(DB_PATH)
        if current:
            print("\nCurrent disclaimer:")
            print("-" * 70)
            print(current)
            print("-" * 70)
        else:
            print("No disclaimer configured in database")
        return 0
    
    # Update with default disclaimer
    print("\nUpdating disclaimer to default text...")
    print("-" * 70)
    print(DEFAULT_DISCLAIMER)
    print("-" * 70)
    
    if set_disclaimer(DB_PATH, DEFAULT_DISCLAIMER):
        print("\n✓ Disclaimer updated successfully!")
        print("\nYou can now:")
        print("1. Edit the disclaimer using:")
        print("   python3 update_disclaimer.py --show  # View current")
        print("2. Or directly in database:")
        print("   sqlite3 mondrian.db \"SELECT value FROM config WHERE key='disclaimer';\"")
        return 0
    else:
        return 1

if __name__ == '__main__':
    sys.exit(main())
